import {Question} from '../class/Question';

const imageDefaultPath: string =
  '../../android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png';

const questionsDB: Question[] = [
  {
    id: 1,
    image: require('./images/01d.png'),
    textQuestion: 'Marque a opção diferente das demais',
    textOptionA: 'Pato A',
    textOptionB: 'Pato B',
    textOptionC: 'Pato C',
    textOptionD: 'Pato D',
    textOptionE: 'Pato E',
    correctOption: 'd',
  },
  {
    id: 2,
    image: require(imageDefaultPath),
    textQuestion: 'Complete a sequência: 21 35 20 34 19 33 18 ??',
    textOptionA: '32',
    textOptionB: '18',
    textOptionC: '40',
    textOptionD: '52',
    textOptionE: '27',
    correctOption: 'a',
  },
  {
    id: 3,
    image: require('./images/03b.png'),
    textQuestion: 'Qual a resposta correta?',
    textOptionA: '6',
    textOptionB: '7',
    textOptionC: '8',
    textOptionD: '9',
    textOptionE: '10',
    correctOption: 'b',
  },
  {
    id: 4,
    image: require(imageDefaultPath),
    textQuestion: 'Tem-se nove velas acesas, e se apagam 3. Quantas ficam?',
    textOptionA: '48 / 4',
    textOptionB: '8 + 1',
    textOptionC: 'dois ao cubo',
    textOptionD: '2 x 3',
    textOptionE: '5-2',
    correctOption: 'e',
  },
  {
    id: 5,
    image: require(imageDefaultPath),
    textQuestion:
      'RELACIONE\n1) acender      ( ? ) riso\n2) pranto     ( ? ) apagar\n3) modéstia     ( ? ) orgulho',
    textOptionA: '213',
    textOptionB: '123',
    textOptionC: '132',
    textOptionD: '312',
    textOptionE: '231',
    correctOption: 'a',
  },
  {
    id: 6,
    image: require(imageDefaultPath),
    textQuestion:
      'Numa sala, de nove cantos, há uma pessoa em cada canto. Quantas pessoas cada uma vê?',
    textOptionA: '10',
    textOptionB: '8',
    textOptionC: '12',
    textOptionD: '7',
    textOptionE: '9',
    correctOption: 'b',
  },
  {
    id: 7,
    image: require('./images/07b.png'),
    textQuestion: 'Qual a alternativa correta?',
    textOptionA: 'Alternativa A',
    textOptionB: 'Alternativa B',
    textOptionC: 'Alternativa C',
    textOptionD: 'Alternativa D',
    textOptionE: 'Alternativa E',
    correctOption: 'b',
  },
  {
    id: 8,
    image: require(imageDefaultPath),
    textQuestion:
      'O rato roeu a roupa da rainha. O rei, revoltado, matou o rato. Quantos erres tem "isso"?',
    textOptionA: 'Um número negativo',
    textOptionB: '3 x 6 : 2',
    textOptionC: '7 vezes zero',
    textOptionD: 'Raiz quadrada de 17',
    textOptionE: 'Cinco ao quadrado',
    correctOption: 'c',
  },
  {
    id: 9,
    image: require(imageDefaultPath),
    textQuestion: 'DRAMA',
    textOptionA: 'dente, rouca, além, algo, diabo',
    textOptionB: 'droga, rapaz, aranha, manga, abacate',
    textOptionC: 'dragão, quartel, arma, marcial, ajudante',
    textOptionD: 'divisão, recruta, mata, mudo, adaga',
    textOptionE: 'lima, rente, arco, monte, ator',
    correctOption: 'b',
  },
  {
    id: 10,
    image: require(imageDefaultPath),
    textQuestion: 'Que se passa aqui?',
    textOptionA: 'mecamitomecamitomecamito',
    textOptionB: 'fitatifofitatifofitatifo',
    textOptionC: 'notanatonotanatonotanota',
    textOptionD: 'tapatipotapatipotapatipo',
    textOptionE: 'fatofotofatofotofatofoto',
    correctOption: 'c',
  },
  {
    id: 11,
    image: require('./images/11e.png'),
    textQuestion: 'Qual figura não pertence ao grupo?',
    textOptionA: 'Imagem A',
    textOptionB: 'Imagem B',
    textOptionC: 'Imagem C',
    textOptionD: 'Imagem D',
    textOptionE: 'Imagem E',
    correctOption: 'e',
  },
  {
    id: 12,
    image: require(imageDefaultPath),
    textQuestion: 'Qual destas perguntas é impossível responder "sim"?',
    textOptionA: 'está dormindo?',
    textOptionB: 'sonhou?',
    textOptionC: 'machucou-se',
    textOptionD: 'vai dormir?',
    textOptionE: 'acordou?',
    correctOption: 'a',
  },
  {
    id: 13,
    image: require(imageDefaultPath),
    textQuestion: 'TEMP -- TEMPES -- TEMPESTA -- ?',
    textOptionA: 'tempestades',
    textOptionB: 'temporal',
    textOptionC: 'tempestade',
    textOptionD: 'tempestuoso',
    textOptionE: 'tempo',
    correctOption: 'c',
  },
  {
    id: 14,
    image: require(imageDefaultPath),
    textQuestion:
      'O professor transmitiu saber riquíssimo a várias gerações, realizando trabalho de grandes extensão: ',
    textOptionA: 'cultural',
    textOptionB: 'regional',
    textOptionC: 'moral',
    textOptionD: 'nacional',
    textOptionE: 'territorial',
    correctOption: 'a',
  },
  {
    id: 15,
    image: require(imageDefaultPath),
    textQuestion: 'Se João fosse Maria, lago seria...',
    textOptionA: 'córrego',
    textOptionB: 'rio',
    textOptionC: 'mar',
    textOptionD: 'riacho',
    textOptionE: 'lagoa',
    correctOption: 'e',
  },
  {
    id: 16,
    image: require(imageDefaultPath),
    textQuestion: 'ATA -- GRAVATA -- AR\nEGO -- PREGO -- ?',
    textOptionA: 'AV',
    textOptionB: 'GO',
    textOptionC: 'GE',
    textOptionD: 'TA',
    textOptionE: 'ER',
    correctOption: 'e',
  },
  {
    id: 17,
    image: require(imageDefaultPath),
    textQuestion: '5  2  9  3  7  --  9\n0  4  1  6  8  --  ?',
    textOptionA: '3',
    textOptionB: '1',
    textOptionC: '4',
    textOptionD: '0',
    textOptionE: '2',
    correctOption: 'b',
  },
  {
    id: 18,
    image: require('./images/18b.png'),
    textQuestion: 'Escolha a alternativa correta',
    textOptionA: '8 / 3',
    textOptionB: '4 / 6',
    textOptionC: '8 / 4',
    textOptionD: '3 / 8',
    textOptionE: '4 / 8',
    correctOption: 'b',
  },
  {
    id: 19,
    image: require(imageDefaultPath),
    textQuestion: 'Que se passa aqui?',
    textOptionA: 'Rua estreita e curta (malar); pssp da face (beco);',
    textOptionB: 'Maior deserto (saara); mamífero desdentado (tatu);',
    textOptionC: 'Imperador romano (Nero); base da montanha (sopé);',
    textOptionD:
      'Ocidente, poente (oeste); livro mais lido do mundo (a Bíblia);',
    textOptionE: 'Mestiço arruivado (sarará); fruto da videira (uva);',
    correctOption: 'a',
  },
  {
    id: 20,
    image: require(imageDefaultPath),
    textQuestion: 'ETNIV SONEM OCNIC',
    textOptionA: 'EZNO',
    textOptionB: 'EZNIUQ',
    textOptionC: 'ETES',
    textOptionD: 'EZERT',
    textOptionE: 'ATNIRT',
    correctOption: 'b',
  },
  {
    id: 21,
    image: require(imageDefaultPath),
    textQuestion:
      'Um passageiro sai, de avião, às 15 horas, do Rio com destino a Manaus, cuja viagem dura 3 horas. Por que, então, ele chegou lá às 17 horas e não às 18 horas?',
    textOptionA: 'Tempo chuvoso',
    textOptionB: 'Imperícia do piloto',
    textOptionC: 'Pouso forçado',
    textOptionD: 'Diferença de fuso horário',
    textOptionE: 'Mudança de rota',
    correctOption: 'd',
  },
  {
    id: 22,
    image: require(imageDefaultPath),
    textQuestion: 'DE CANA\nFRIO\nCHATO\nQUENTE',
    textOptionA: 'gomo',
    textOptionB: 'talo',
    textOptionC: 'pé',
    textOptionD: 'só',
    textOptionE: 'nó',
    correctOption: 'c',
  },
  {
    id: 23,
    image: require(imageDefaultPath),
    textQuestion: 'Quinhentos, igual a:',
    textOptionA: '2 x 5 ao quadrado + 15 x 40',
    textOptionB: '2 ao quadrado x 5 ao quadrado + 50 x 4',
    textOptionC: '2 à quarta potência x 5 ao quadrado + 50 x 4',
    textOptionD: '2 ao quadrado x 3 x 5 ao quadrado + 25 x 6',
    textOptionE: '2 ao cubo x 5 ao quadrado + 75 x 4',
    correctOption: 'e',
  },
  {
    id: 24,
    image: require('./images/24b.png'),
    textQuestion: 'Indique a opção correta',
    textOptionA: '7, 7, 7',
    textOptionB: '8, 7, 7',
    textOptionC: '8, 8, 8',
    textOptionD: '6, 7, 8',
    textOptionE: '7, 8, 7',
    correctOption: 'e',
  },
  {
    id: 25,
    image: require('./images/25a.png'),
    textQuestion: 'Qual a figura correta?',
    textOptionA: 'Figura A',
    textOptionB: 'Figura B',
    textOptionC: 'Figura C',
    textOptionD: 'Figura D',
    textOptionE: 'Figura E',
    correctOption: 'a',
  },
  {
    id: 26,
    image: require(imageDefaultPath),
    textQuestion:
      'Quando se está num quarto escuro e se tem um fósforo, um fogareiro, um lampião, uma vela e um cigarro, o que se acende primeiro?',
    textOptionA: 'Fósforo',
    textOptionB: 'Fogareiro',
    textOptionC: 'Lampião',
    textOptionD: 'Vela',
    textOptionE: 'Cigarro',
    correctOption: 'a',
  },

  //Add more questions here
];

export default questionsDB;
